const brandsList = {
    'شیائومی' : 'Xiaomi',
    'سامسونگ' : 'Samsung',
    'اپل' : 'Apple',
    'IPHONE' : 'Apple',
    'نوکیا' : 'Nokia',
    'هوآوی' : 'Huawei',
    'هواوی' : 'Huawei',
    'موتورولا' : 'motorola',
    'لیتو' : 'Leitu',
    'دبلیو یو دبلیو' : 'WUW',
    'کوکلایسک' : 'Kuclassic',
    'کوکلاسیک' : 'Kuclassic',
    'بیبوشی' : 'Biboshi',
    'بییوشی' : 'Biboshi',
    'کلومن' : 'Koluman',
    'ترانیو' : 'Tranyoo',
    'اچ اند ام' : 'H&M',
    'ریمکس' : 'Remax',
    'یونیمات' : 'Unimat',
    'جانتا' : 'Janta',
    'ویفینگ' : 'Weifeng',
    'SLCN' : 'SLCN',
    'یونیورسال' : 'Universal',
    'انکر' : 'Anker',
    'OK Stand' : 'OK Stand',
    'پاناسون' : 'Panasun',
    'ایوون' : 'Ivon',
    'inpods' : 'inpods',
    'Inpods' : 'inpods',
    'ایرفون' : 'Earphones',
    'M106' : 'M106',
    'BTH-F9-5' : 'BTH-F9-5',
    'تی پی-لینک' : 'TP-Link',
    'جی پلاس' : 'GPlus',
    'بیاند' : 'Beyond',
    'ای دیتا' : 'ADATA',
    'جی تب' : 'G-Tab',
    'وسترن دیجیتال' : 'Western Digital',
    'T36' : 'T36',
    '4D' : '4D',
    'ریزر' : 'Razer',
    'تسکو' : 'Tsco',
    'اچ اکس اس' : 'HXX',
    'اچ ایکس اس' : 'HXX',
    'کوئین تک' : 'Queen Tech',
    'G9' : 'G9',
    'G24' : 'G24',
    'W26' : 'W26',
    'HW16' : 'HW16',
    'M36' : 'M36',
    'marbel' : 'marbel',
    'اچ‌پی' : 'HP',
    'اچ پی' : 'HP',
    'سن دیسک' : 'SanDisk',
    'رویال' : 'Royal',
    'میدسان' : 'Midsun',
    'مودیو' : 'Modio',
    'هایلو' : 'Haylou',
    'لوکا' : 'Lucca',
    'امیزفیت' : 'Amazfit',
    'میبرو' : 'Mibro',
    'اچ ام' : 'HM',
    'لنوو' : 'Lenovo',
    'جی ال ایکس' : 'GLX',
    'مایکروسافت' : 'Microsoft',
    'ایسوس' : 'Asus',
    'ام اس آی' : 'MSI',
    'الین ویر' : 'AlienWare',
    'ایسر' : 'Acer',
    'کانن' : 'Canon',
    'پاناسونیک' : 'Panasonic',
    'اسمال سان' : 'Small Sun',
    'کاسیو' : 'Casio',
    'کیتک' : 'Keytec',
    'یونیک' : 'Unic',
    'آلکاتل' : 'Alcatel',
    'دایمو' : 'Dymo'
};


module.exports = {
    brandsList
};